### ISSUE TITLE
Container crashed due to invalid instruction in argon2.so, under Haswell or older

### ISSUE THREAD

**Issue by nroach44** [convos-chat/convos#862] opened 2023-10-26 02:25 UTC
**Describe the bug**
When attempting to run this container on a machine with an Ivy Bridge / Haswell CPU, the container will start up, but when "logging in" to create a password, the container dies.

The following is seen in syslog:

````
Oct 26 09:57:55 uranus kernel: traps: perl[144999] trap invalid opcode ip:7f626e209811 sp:7ffedc4b5b10 error:0 in Argon2.so[7f626e206000+5000]
````

Since that file seems to live at `/diff/app/local/lib/perl5/x86_64-linux-thread-multi/auto/Crypt/Argon2/Argon2.so` in the container's work dir, I'm logging it here. If it should be filed against the main container let me know.

Since Haswell and Ivy Bridge are old, but still quite capable for self hosting, and there's no mention of required CPU functions for x86_64 on the Alpine Linux wiki, I believe this to be a bug.

**To Reproduce**
Run the container on a machine with an Ivy Bridge or Haswell CPU.

**Expected behavior**
Container runs without issue.

**Screenshots**
Nil

**Environment:**
Debian 12, podman.

**Comment by stigtsp** [comment] 2023-10-26 10:29
Maybe relevant upstream issue:
- https://github.com/Leont/crypt-argon2/issues/12

**Comment by stigtsp** [comment] 2023-10-26 11:56
Hi @nroach44 

This is likely caused by the issue linked above, where Crypt::Argon2 is built using `-march=native`. I hope this will be fixed soon. In the meanwhile, you can try to rebuild the docker container on your machine - it should work.

**Comment by jhthorsen** [comment] 2024-03-18 01:25
@nroach44, @trymbill, @jberger: If you have some time to spare, could you test [v8.06](https://github.com/convos-chat/convos/pkgs/container/convos/192111564?tag=v8.06)?

**Comment by nroach44** [comment] 2024-03-20 08:55
`#worksForMe`

Both in general and when changing my password to a temp password, logging out and back in, and then changing it again.

**Comment by jberger** [comment] 2024-03-20 15:28
I'm not having luck with v8.06. Still cannot login, the pod crashes when attempting. I will also note however that the help page displays v8.05 even when I've deployed v8.06. Is there an easy way to confirm which code I'm running?

**Comment by jhthorsen** [comment] 2024-03-20 23:30
I'm going to close this issue, since it seems resolved.

**Closed by jhthorsen** 2024-03-20 23:30 UTC
Labels: bug, help wanted
