### ISSUE TITLE
GUI option to show if the user is away

### ISSUE THREAD

**Issue by acagastya** [convos-chat/convos#629] opened 2021-11-24 04:50 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no straightforward way to see if a user has `/away` set, or not.  If they have, there is no straightforward way of seeing their away message.

**Describe the solution you'd like**
I would suggest, for channels, the nick list on the right-hand should have a visual indication, an icon (💤 perhaps?) that the person is afk.  A tool-tip on hover can have the away message displayed.  And the nick has a CSS class of "user-away" which might have lower opacity.

<img width="269" alt="Screenshot 2021-11-24 at 04 43 22" src="https://user-images.githubusercontent.com/5466083/143176630-666e4595-f6cd-4336-b5a3-a10b165b5ede.png">

<img width="269" alt="Screenshot 2021-11-24 at 04 44 51" src="https://user-images.githubusercontent.com/5466083/143176656-eb15bc5c-5e9d-4b8d-a535-fbbadbdd2ca4.png">

For private chat, away message  next to their nick?

<img width="423" alt="Screenshot 2021-11-24 at 04 47 22" src="https://user-images.githubusercontent.com/5466083/143176696-eaa50ee5-3b4f-4d7d-af2b-c6891ea29783.png">

And perhaps a GUI way to set an away message would also come really handy.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by jhthorsen** [comment] 2021-11-24 05:24
I'm pretty sure this is a duplicate of #360 and I think what you want is impossible, since it doesn't scale for channels with ~1000 users.

Based on that, I'm afraid I have to close those issue.

**Closed by jhthorsen** 2021-11-24 05:24 UTC
Labels: duplicate

**Comment by acagastya** [comment] 2021-11-24 06:07
@jhthorsen if it can't be scaled for large channels, how about just for PMs?  That and an easy way to set an away message should still be do-able, right?

**Comment by jhthorsen** [comment] 2021-11-24 06:16
Yes, and it's covered here: https://github.com/convos-chat/convos/issues/360#issuecomment-927092187
